spring:
  application:
    name: exam-solver-openai

server:
  port: 8081

openai:
  api-key: ${OPENAI_API_KEY}
  url: https://api.openai.com/v1
  model:
    text: gpt-4o-mini
    vision: gpt-4o-mini-vision
    fallback: gpt-4o
  timeout:
    connect: 5s
    write: 3s
    read: 30s
    text: 10s
  max-retries: 2
  max-concurrent: 4
  retry:
    initial-delay: 300ms
    max-delay: 3s

logging:
  level:
    com.examsolver.openai: INFO
    org.springframework.web: WARN
