openai:
  api-key: dummy
  url: http://localhost/stub
  model:
    text: stub-text
    vision: stub-vision
    fallback: stub-fallback
  timeout:
    connect: 100ms
    write: 100ms
    read: 200ms
    text: 500ms
  max-retries: 0
  max-concurrent: 1
  stub:
    latency: 150ms
    error-rate: 0.0
