spring:
  application:
    name: exam-solver-openai

openai:
  api-key: ${OPENAI_API_KEY}
  url: https://api.openai.com/v1/chat/completions
  model:
    text: gpt-4o-mini           # antes: default-model
    vision: gpt-4o-mini-vision  # antes: vision-model
    fallback: gpt-4o            # antes: fallback-model
  timeout:
    connect: 5s
    read: 30s
    text: 10s
  max-retries: 2
  max-concurrent: 4
  retry:
    initial-delay: 300ms
    max-delay: 3s

logging:
  level:
    com.examsolver.openai: INFO
    org.springframework.web: WARN
